"""Add status to request

Revision ID: 0563a86cb7fb
Revises: 8f8f4a0ca135
Create Date: 2024-10-24 15:41:01.467854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0563a86cb7fb'
down_revision: Union[str, None] = '8f8f4a0ca135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="created"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'status')
    # ### end Alembic commands ###
