"""Add created_at and updated_at for requests table

Revision ID: 8f8f4a0ca135
Revises: 2987c7cee068
Create Date: 2024-10-24 14:12:11.725754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f8f4a0ca135'
down_revision: Union[str, None] = '2987c7cee068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('requests', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'updated_at')
    op.drop_column('requests', 'created_at')
    # ### end Alembic commands ###
